// Package xsdgen generates Go source code from xml schema documents.
//
// The xsdgen package generates type declarations and accompanying
// methods for marshalling and unmarshalling XML elements that adhere
// to an XML schema. The source code generation is configurable, and can
// be passed through user-defined filters.
//
// Code generated by the xsdgen package is self-contained; only the Go
// standard library is used. All types generated by the xsdgen package
// can be unmarshalled into by the standard encoding/xml package. Where
// neccessary, methods are generated to satisfy the interfaces used by
// encoding/xml.
package xsdgen
