// Code generated by "stringer -type=Builtin"; DO NOT EDIT.

package xsd

import "strconv"

const _Builtin_name = "AnyTypeENTITIESENTITYIDIDREFIDREFSNCNameNMTOKENNMTOKENSNOTATIONNameQNameAnyURIBase64BinaryBooleanByteDateDateTimeDecimalDoubleDurationFloatGDayGMonthGMonthDayGYearGYearMonthHexBinaryIntIntegerLanguageLongNegativeIntegerNonNegativeIntegerNonPositiveIntegerNormalizedStringPositiveIntegerShortStringTimeTokenUnsignedByteUnsignedIntUnsignedLongUnsignedShortXMLLangXMLSpaceXMLBaseXMLIdAnySimpleType"

var _Builtin_index = [...]uint16{0, 7, 15, 21, 23, 28, 34, 40, 47, 55, 63, 67, 72, 78, 90, 97, 101, 105, 113, 120, 126, 134, 139, 143, 149, 158, 163, 173, 182, 185, 192, 200, 204, 219, 237, 255, 271, 286, 291, 297, 301, 306, 318, 329, 341, 354, 361, 369, 376, 381, 394}

func (i Builtin) String() string {
	if i < 0 || i >= Builtin(len(_Builtin_index)-1) {
		return "Builtin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Builtin_name[_Builtin_index[i]:_Builtin_index[i+1]]
}
